# Generated by Django 6.0.2 on 2026-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customerprofile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
