# Generated by Django 6.0.2 on 2026-03-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categories_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=255, unique=True),
        ),
    ]
