# Generated by Django 6.0.4 on 2026-05-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_delete_expired_otps_periodic_task'),
        ('accounts', '0003_alter_user_is_active'),
    ]

    operations = [
    ]
