# Generated by Django 6.0.4 on 2026-05-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_update_periodic_task_name'),
        ('accounts', '0004_merge_20260501_1818'),
    ]

    operations = [
    ]
